# Generated by Django 2.2.2 on 2019-06-10 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20190610_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Photo'),
        ),
    ]
